name: 'PR Validation'
on:
  pull_request_target: 
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  pre-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@2.0.0 # pinned to latest
    secrets: inherit
    with:
      subjectPattern: '^.+$'